---
- name: Ensure group "docker" exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Adding user {{ autoreduction_user }} to `docker` group to allow sudoless docker usage
  user: name={{ autoreduction_user }}
        group={{ autoreduction_user }}
        shell=/bin/bash
        password=${password}
        groups=docker
        append=yes

- name: Add .autoreduce folder
  file:
    path: "/home/{{ autoreduction_user }}/.autoreduce/"
    state: directory
    mode: '0755'
    owner: "{{ autoreduction_user }}"
    group: "{{ autoreduction_user }}"

- name: Copy backup scripts
  copy:
    src: last_runs.csv
    dest: "/home/{{ autoreduction_user }}/.autoreduce/last_runs.csv"
    mode: 0700
    owner: "{{ autoreduction_user }}"

- name: Set run_command depending on deployment stage
  include_vars: "{{ deployment_stage }}.yml"

- name: Copy run-run-detection script
  template:
    src: run-run-detection.sh.j2
    dest: "/home/{{ autoreduction_user }}/run-run-detection.sh"
    mode: 0500
    owner: "{{ autoreduction_user }}"

- name: Run run-detection every minute
  become: yes
  become_user: "{{ autoreduction_user }}"
  ansible.builtin.cron:
    name: "Run run-detection every minute"
    job: "bash run-run-detection.sh"
