---

- name: Add .autoreduce folder
  file:
    path: "/home/{{ autoreduction_user }}/.autoreduce/"
    state: directory
    mode: '0755'
    owner: "{{ autoreduction_user }}"
    group: "{{ autoreduction_user }}"

- name: Copy backup scripts
  copy:
    src: last_runs.csv
    dest: "/home/{{ autoreduction_user }}/.autoreduce/last_runs.csv"
    mode: 0700
    owner: "{{ autoreduction_user }}"

- name: Start the container
  community.docker.docker_container:
    name: run-detection
    image: ghcr.io/autoreduction/autoreduce-run-detection:latest
    state: started
    pull: true
    env:
      AUTOREDUCTION_PRODUCTION: "true"
      AUTOREDUCE_TOKEN: "{{ vault_run_detection_token }}"
    volumes:
      - /home/{{ autoreduction_user }}/.autoreduce:/home/{{ autoreduction_user }}/.autoreduce:rw
      - /instrument:/instrument:rw
      - /isis:/isis
      - /shared-config:/shared-config
    detach: yes
    network_mode: host
    comparisons:
      image: strict

- name: Copy run-run-detection script
  template:
    src: run-run-detection.sh.j2
    dest: "/home/{{ autoreduction_user }}/run-run-detection.sh"
    mode: 0500
    owner: "{{ autoreduction_user }}"

- name: Run run-detection every minute
  become: yes
  become_user: "{{ autoreduction_user }}"
  ansible.builtin.cron:
    name: "Run run-detection every minute"
    job: "bash run-run-detection.sh >> ~/job-output.log"
