sudo: required
language: python
python:
  - "3.7"

dist: xenial

addons:
  apt:
    packages:
    - activemq

install:
  # Install autoreduction
  - pip3 install -e .
  # Install test suite dependencies
  - pip3 install -r requirements.txt

before_script:
  # Migrate test settings
  - /usr/bin/activemq start &
  - sleep 5  # Sleep to give AMQ enough time to start up
  - python3 src/build_config/setup_tests.py

script:
  # ================ Functional tests =============== #
  - echo "Running Unit tests"
  - py.test --cov=src

  # ================ Static Analysis ================= #
  - pylint src

after_success:
  - coveralls
