run_command: >
  --volume /home/isisautoreduce/.autoreduce:/home/isisautoreduce/.autoreduce
  --volume /isis:/isis
  --volume /isis:/archive
  --volume /shared-config:/shared-config
  --name run-detection
  --rm
  --network=host
