run_command: >
  --env AUTOREDUCTION_PRODUCTION=true
  --env AUTOREDUCE_TOKEN={{ vault_run_detection_token }}
  --volume /home/{{ autoreduction_user }}/.autoreduce:/home/{{ autoreduction_user }}/.autoreduce
  --volume /isis:/isis
  --volume /isis:/archive
  --volume /shared-config:/shared-config
  --name run-detection
  --network=host
